// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace test2.Models
{
    public partial class Guardians
    {
        [JsonIgnore]
        public int GuardianId { get; set; }
        public int Sdid { get; set; }
        public string GuardianFirstName { get; set; } = null!;
        public string GuardianLastName { get; set; } = null!;
        public string GuardianEmail { get; set; } = null!;
        public long? GuardianPhone { get; set; }
        public string UserCreated { get; set; } = null!;
        public DateTime? UserCreatedDateTime { get; set; }
        public string? UserUpdated { get; set; }
        public DateTime? UserUpdatedDateTime { get; set; }

        [JsonIgnore]
        public virtual SurveyInfo? Sd { get; } = null!;
    }
}
